"""Where generated audio lives. Takes reference it by `audio_key`, never by path or URL.

`AudioStore` is a Protocol (structural typing, like a TypeScript interface): anything with
`put` and `get` of the right shape satisfies it, no inheritance needed. `LocalAudioStore`
writes to a directory and is the v1 implementation; the object-store one (MinIO/S3, week 8)
replaces it without touching the services.

Blocking file I/O is pushed to a worker thread with `asyncio.to_thread`, so a large write
does not stall the event loop.
"""

import asyncio
from pathlib import Path
from typing import Protocol


class AudioNotFound(LookupError):
    """No audio is stored under this key (deleted, never written, or wrong store)."""


class AudioStore(Protocol):
    async def put(self, key: str, data: bytes) -> None: ...

    async def get(self, key: str) -> bytes: ...


class LocalAudioStore:
    def __init__(self, root: Path) -> None:
        self._root = Path(root).resolve()

    def __repr__(self) -> str:
        return f"LocalAudioStore(root={str(self._root)!r})"

    async def put(self, key: str, data: bytes) -> None:
        path = self._path_for(key)
        await asyncio.to_thread(self._write, path, data)

    async def get(self, key: str) -> bytes:
        path = self._path_for(key)
        try:
            return await asyncio.to_thread(path.read_bytes)
        except FileNotFoundError:
            raise AudioNotFound(key) from None

    @staticmethod
    def _write(path: Path, data: bytes) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    def _path_for(self, key: str) -> Path:
        """Keys are relative POSIX paths ("takes/<uuid>.mp3"). Anything that could escape the
        root is refused: keys are generated by our own code, so this is a programming error.

        The check is on the *resolved* path, not on the key's text: on Windows `Path` treats a
        backslash as a separator and a drive-letter path as absolute, which a POSIX-only check would
        miss. Backslashes are refused outright so a key means the same on every platform."""
        if not key or "\\" in key:
            raise ValueError(f"invalid audio key: {key!r}")
        path = (self._root / key).resolve()
        if path == self._root or not path.is_relative_to(self._root):
            raise ValueError(f"invalid audio key: {key!r}")
        return path
